# For more info on Python, GitHub Actions, and Azure App Service 
# please head to https://aka.ms/python-webapps-actions

name: Build and deploy Django app to Azure App Service

on:
  push:
    branches: 
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup Python version
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Create and start virtual environment
      run: |
        python3 -m venv venv
        source venv/bin/activate

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests
      run: python manage.py test
  
  deploy-to-webapp:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Build for App Service
        uses: azure/appservice-build@v2
        with:
          platform: python
          platform-version: '3.8'

      - name: Deploy to App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'freeberg-django'
          publish-profile: ${{ secrets.your_publish_profile_secret_name }}
