# For more info on Python, GitHub Actions, and Azure App Service 
# please head to https://aka.ms/python-webapps-actions

name: Build and deploy Django app to Azure App Service

on:
  push:
    branches: 
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup Python version
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Create and start virtual environment
      run: |
        python3 -m venv venv
        source venv/bin/activate

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Collect static
      run: python manage.py collectstatic

    - name: Upload artifact for deployment jobs
      uses: actions/upload-artifact@v2
      with:
        name: python-app
        path: |
          . 
          !venv/

    - name: Run tests
      run: python manage.py test
  
  deploy-to-webapp:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: python-app
          path: .

      - name: Log in to Azure CLI
        with:
          creds: ${{ secrets.AZURE_SERVICE_PRINCIPAL }}
    
      - name: Disable static collection on App Service
        run: |
          az webapp 

      - name: Deploy to App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'freeberg-django'
          publish-profile: ${{ secrets.your_publish_profile_secret_name }}
